name = input ("Enter name: ")
major = input ("Enter major: ")
year = input ("Enter year: ")
group = input ("Enter group: ")
age = input ("Enter age: ")
location = input ("Enter location: ")
hobby = input ("Enter hobby: ")
Email = input ("Enter Email: ")
siblings = input ("Enter siblings: ")
laptoptype = input("Enter laptoptype: ") 
print (name)
print(major)
print (year)
print (group)
print (int(age))
print(location)
print (hobby)
print (Email)
print (siblings)
print (laptoptype)